name: Build and Push Docker

on:
  push:
    branches: [main]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check Out Repo
        uses: actions/checkout@v2

      - name: Login to Canister
        uses: docker/login-action@v1
        with:
          registry: cloud.canister.io:5000
          username: ${{ secrets.CANISTER_USERNAME }}
          password: ${{ secrets.CANISTER_PASSWORD }}

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Build image
        uses: docker/build-push-action@v2
        with:
          context: ./
          push: true
          file: ./Dockerfile
          tags: cloud.canister.io:5000/quentinbardenet/velocargo-api:latest

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}

      - name: deploy containers
        uses: garygrossgarten/github-action-ssh@release
        with:
          command: cd /home/ubuntu/velocargo && ./deploy.sh
          host: ${{ secrets.HOST }}
          username: ubuntu
          privateKey: ${{ secrets.PRIVATE_KEY }}
